apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
    - name: terraform
      image: hashicorp/terraform
      command: ["sh", "-c", "echo 'Checking Terraform version...' && terraform version && sleep 3600"]
      tty: true
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcp/credentials.json  # Path to where credentials are mounted
      volumeMounts:
        - name: gcp-credentials
          mountPath: /etc/gcp
          readOnly: true
  volumes:
    - name: gcp-credentials
      secret:
        secretName: allow-gcp-resource-create-and-manage  # Secret name
